name: private-voice-chat-workflow

on:
  workflow_dispatch:

jobs:
  signaling_server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      FLASK_PORT: 8000
      LOG_LEVEL: INFO
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask==3.0.3 flask-socketio==5.3.6 eventlet==0.35.2

      - name: Start signaling server
        run: |
          nohup gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:${FLASK_PORT} signaling:app &
          sleep 5
          curl --fail http://localhost:${FLASK_PORT}/ping

      - name: Output server URL
        run: echo "Signaling server listening on port ${FLASK_PORT}"
